'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MCDO.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _04e9faefec96d862d481efc5703d8b3f() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("04e9faefec96d862d481efc5703d8b3f", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _84554726_3967160099964455_5619477631754829824_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("84554726_3967160099964455_5619477631754829824_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property brr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property c() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Family_Size_Merch_cover_photo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Family Size Merch cover photo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__13_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image_removebg_preview__13_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__14_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-removebg-preview (14)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__15_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-removebg-preview (15)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__16_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image_removebg_preview__16_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__17_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image_removebg_preview__17_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__18_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image_removebg_preview__18_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__19_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image_removebg_preview__19_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__20_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image_removebg_preview__20_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__21_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-removebg-preview (21)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__22_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-removebg-preview (22)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__23_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-removebg-preview (23)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__23_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-removebg-preview (23)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__24_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-removebg-preview (24)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__25_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-removebg-preview (25)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__26_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-removebg-preview (26)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__27_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-removebg-preview (27)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__28_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-removebg-preview (28)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__29_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-removebg-preview (29)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__30_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-removebg-preview (30)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__31_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-removebg-preview (31)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__32_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-removebg-preview (32)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__33_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-removebg-preview (33)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__34_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-removebg-preview (34)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__35_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-removebg-preview (35)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__36_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-removebg-preview (36)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__37_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-removebg-preview (37)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__38_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-removebg-preview (38)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__39_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-removebg-preview (39)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__40_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-removebg-preview (40)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__41_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-removebg-preview (41)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__42_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-removebg-preview (42)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_removebg_preview__43_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image-removebg-preview (43)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property v() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("v", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property z() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("z", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
